theme: jekyll-theme-cayman  # Or any theme from GitHub Pages-supported themes
title: Cloud Operations
baseurl: "/CloudOps-Confluence"  ## Set the baseurl to your repository name
plugins:
  - jekyll-include-cache

