title: Cloud Operations
description: "All important documentation about cloud operations"
baseurl: "/CloudOps-Confluence"
url: "https://vchinnap.github.io"
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate: 10
paginate_path: "/page:num/"

author:
  name: Vinod
  email: your.email@example.com
  social:
    github: vchinnap
    linkedin: your-linkedin-url
    twitter: yourtwitterhandle

exclude:
  - README.md
  - /drafts/

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
