theme: jekyll-theme-slate
title: My Project Documentation
description: All the important information about My Project
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: "/CloudOps-Confluence"
