title: CloudOps-Confluence
description: "All important discussions and documentation about Cloud Operations updated"
baseurl: "/CloudOps-Confluence"
theme: jekyll-theme-hacker
plugins:
  - jekyll-toc
github:
  is_project_page: false
