title: Cloud Operations
description: "All important discussions and documentation about Cloud Operations updated"
baseurl: "/CloudOps-Confluence"
theme: jekyll-theme-cayman
plugins:
  - jekyll-toc
#github:
 # is_project_page: false
