theme: jekyll-theme-cayman  # You can choose another theme if you'd like
title: My Project Documentation
description: All the important information about My Project
baseurl: "/CloudOps-Confluence"  # Replace with your repository name
