name: Get Discussions Count by Category

on:
  workflow_dispatch:

jobs:
  get-discussions-count-by-category:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch Discussions Count by Category
      id: get_count_by_category
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        python - <<EOF
        import requests
        import json
        import os

        url = f"https://api.github.com/repos/{os.environ['GITHUB_REPOSITORY']}/discussions"
        headers = {
            'Authorization': f"Bearer {os.environ['GITHUB_TOKEN']}",
            'Accept': 'application/vnd.github.v3+json'
        }
        response = requests.get(url, headers=headers)

        count_by_category = {}
        if response.status_code == 200:
            discussions = response.json()
            for discussion in discussions:
                category_name = discussion['category']['name']
                count_by_category[category_name] = count_by_category.get(category_name, 0) + 1
        else:
            print(f"Failed to fetch discussions. Status code: {response.status_code}")

        with open('discussions_by_category.json', 'w') as f:
            json.dump(count_by_category, f)

        print(f"discussions_by_category={json.dumps(count_by_category)}")
        EOF

    - name: Display Discussions Count by Category
      run: cat discussions_by_category.json

    - name: Set Discussions Count by Category as Output
      id: set_output
      run: |
        discussions_by_category=$(jq -c '.' discussions_by_category.json)
        echo "discussions_by_category=$discussions_by_category" >> $GITHUB_OUTPUT

    - name: Print Discussions Count by Category in Workflow
      run: |
        echo 'The count of discussions by category is:'
        echo '${{ steps.set_output.outputs.discussions_by_category }}' | jq '.'
