name: Get Discussions Count by Label

on:
  workflow_dispatch:

jobs:
  get-discussions-count-by-label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch Discussions Count by Label
      id: get_count_by_label
      env:
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      run: |
        python - <<EOF
        import requests
        import json
        import os

        url = f"https://api.github.com/repos/{os.environ['GITHUB_REPOSITORY']}/discussions"
        headers = {
            'Authorization': f"Bearer {os.environ['GITHUB_TOKEN']}",
            'Accept': 'application/vnd.github.v3+json'
        }
        response = requests.get(url, headers=headers)

        count_by_label = {}
        if response.status_code == 200:
            discussions = response.json()
            for discussion in discussions:
                if not discussion['labels']:
                    count_by_label['No Label'] = count_by_label.get('No Label', 0) + 1
                else:
                    for label in discussion['labels']:
                        label_name = label['name']
                        count_by_label[label_name] = count_by_label.get(label_name, 0) + 1
        else:
            print(f"Failed to fetch discussions. Status code: {response.status_code}")

        with open('discussions_by_label.json', 'w') as f:
            json.dump(count_by_label, f, indent=2)

        print(f"discussions_by_label={json.dumps(count_by_label)}")
        EOF

    - name: Display Discussions Count by Label
      run: cat discussions_by_label.json

    - name: Set Discussions Count by Label as Output
      id: set_output
      run: |
        discussions_by_label=$(cat discussions_by_label.json)
        echo "discussions_by_label=$discussions_by_label" >> $GITHUB_OUTPUT

    - name: Print Discussions Count by Label in Workflow
      run: |
        echo "The count of discussions by label is: ${{ steps.set_output.outputs.discussions_by_label }}"
