import requests
import json

# Fetch discussions from the GitHub repository
url = 'https://api.github.com/repos/vchinnap/CloudOps-Discussions/discussions'
headers = {'Authorization': 'Bearer YOUR_ACCESS_TOKEN', 'Accept': 'application/vnd.github.v3+json'}
response = requests.get(url, headers=headers)

# Count discussions by label
count_by_label = {}
if response.status_code == 200:
    discussions = response.json()
    for discussion in discussions:
        if not discussion['labels']:
            count_by_label['No Label'] = count_by_label.get('No Label', 0) + 1
        else:
            for label in discussion['labels']:
                label_name = label['name']
                count_by_label[label_name] = count_by_label.get(label_name, 0) + 1
else:
    print(f"Failed to fetch discussions. Status code: {response.status_code}")

# Store the counted discussions by label into a JSON file
with open('discussions_by_label.json', 'w') as f:
    json.dump(count_by_label, f, indent=2)

# Display the contents of discussions_by_label.json
with open('discussions_by_label.json', 'r') as f:
    discussions_by_label = json.load(f)

print("Discussions count by label:")
print(json.dumps(discussions_by_label, indent=2))
