name: Count Discussions

on:
  workflow_dispatch:

jobs:
  count-discussions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @octokit/graphql node-fetch

      - name: Count discussions
        env:
          G_TOKEN: ${{ secrets.G_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          node -e "
          const runGraphQLQuery = async () => {
            const { graphql } = await import('@octokit/graphql');
            const fetch = (await import('node-fetch')).default;
          
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            console.log('Owner:', owner);
            console.log('Repo:', repo);
          
            const query = \`
              query(\$owner: String!, \$repo: String!) {
                repository(owner: \$owner, name: \$repo) {
                  discussions {
                    totalCount
                  }
                }
              }
            \`;
          
            try {
              const result = await graphql({
                query,
                variables: { owner, repo },
                headers: {
                  authorization: \`token \${process.env.G_TOKEN}\`,
                },
                request: {
                  fetch: fetch
                }
              });
          
              console.log(\`Total discussions: \${result.repository.discussions.totalCount}\`);
            } catch (error) {
              console.error('Error:', error);
              if (error.errors) {
                error.errors.forEach(e => console.error('GraphQL Error:', e.message));
              }
            }
          };
          
          runGraphQLQuery();
          "
