name: Enforce Category-Specific and Non-Empty Labels

on:
  discussion:
    types: [created, edited]

jobs:
  enforce_category_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Validate category and labels
        uses: actions/github-script@v6
        with:
          script: |
            const { discussion } = context.payload;

            // Extract category and labels from the payload
            const category = discussion.category?.name;
            const labels = discussion.labels || [];

            console.log(`Category: ${category}`);
            console.log(`Labels: ${labels.length > 0 ? labels.map(label => label.name) : 'No labels applied'}`);

            // Define allowed labels for each category
            const allowedLabels = {
              'ServiceNow': ['incident', 'chg'],  // Case-sensitive allowed labels for ServiceNow
              'JIRA': ['bug', 'task', 'story']
            };

            // Check if the category is one we're validating
            if (allowedLabels[category]) {
              const requiredLabels = allowedLabels[category];

              // If there are no labels, add a comment requesting labels
              if (labels.length === 0) {
                console.log(`No labels found for category "${category}". Adding a comment to the discussion...`);
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: discussion.number,
                  body: `**Label issue detected for the category "${category}".**\n` +
                        `Please use one of the allowed labels:\n` +
                        `- For ServiceNow: "Incident", "CHG"\n` +
                        `- For JIRA: "Bug", "Task", "Story"\n` +
                        `- **No discussion should be created without at least one valid label.**`
                });
                return;
              }

              // Validate the labels
              const hasValidLabel = labels.some(label => requiredLabels.includes(label.name.toLowerCase()));

              if (!hasValidLabel) {
                console.log(`Invalid labels for category "${category}". Adding a comment to the discussion...`);
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: discussion.number,
                  body: `**Invalid label issue detected for the category "${category}".**\n` +
                        `Allowed labels are: ${requiredLabels.join(', ')}.\n` +
                        `Please update the labels accordingly.`
                });
                return;
              }
            } else {
              console.log(`Invalid category "${category}". Adding a comment to the discussion...`);
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: discussion.number,
                body: `**Invalid category detected.**\n` +
                      `Please select a valid category.`
              });
            }
