name: Print Discussion Payload for Debugging

on:
  discussion:
    types: [created, edited]

jobs:
  print_discussion_payload:
    runs-on: ubuntu-latest

    steps:
      - name: Print entire discussion payload
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Full discussion payload:', JSON.stringify(context.payload, null, 2));
