name: Count Discussions by Category

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  count_discussions_by_category:
    runs-on: ubuntu-latest

    steps:
      - name: Get discussions count by category
        uses: actions/github-script@v6
        with:
          script: |
            // Fetch discussions for the repository using discussions API
            const allDiscussions = await github.paginate(github.rest.teams.listDiscussionsInOrg, {
              org: context.repo.owner,
              team_slug: context.repo.repo, // Assuming discussions are in this repository
            });

            // Initialize an empty object to store category counts
            const categoryCounts = {};

            // Loop through discussions and count by category
            allDiscussions.forEach(discussion => {
              const category = discussion.category.name;
              if (categoryCounts[category]) {
                categoryCounts[category] += 1;
              } else {
                categoryCounts[category] = 1;
              }
            });

            // Log the category counts in JSON format
            console.log(JSON.stringify(categoryCounts, null, 2));

            // Optionally, display the data in table format
            console.table(categoryCounts);
