name: Count Discussions by Category

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  count_discussions_by_category:
    runs-on: ubuntu-latest

    steps:
      - name: Get discussions count by category
        uses: actions/github-script@v6
        with:
          script: |
            // Fetch all issues from the repository (discussions are treated like issues)
            const allIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',  // Fetch both open and closed issues (discussions)
              per_page: 100  // Adjust as needed
            });

            // Initialize an empty object to store category counts
            const categoryCounts = {};

            // Loop through issues and filter discussions by checking the category field
            allIssues.data.forEach(issue => {
              if (issue.pull_request) return;  // Skip pull requests

              if (issue.discussion_category) {  // Only discussions have a category
                const category = issue.discussion_category.name;
                if (categoryCounts[category]) {
                  categoryCounts[category] += 1;
                } else {
                  categoryCounts[category] = 1;
                }
              }
            });

            // Log the category counts in JSON format
            console.log(JSON.stringify(categoryCounts, null, 2));

            // Optionally, display the data in table format
            console.table(categoryCounts);
