name: Enforce Category-Specific and Non-Empty Labels

on:
  discussion:
    types: [created, edited]

jobs:
  enforce_category_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check if discussion payload exists
        id: check_payload
        uses: actions/github-script@v6
        with:
          script: |
            const { discussion } = context.payload;

            // Check if discussion object exists
            if (!discussion) {
              core.setFailed('Discussion object not found in payload.');
              return;
            }

            const category = discussion.category?.name;
            const labels = discussion.labels?.map(label => label.name.toLowerCase());

            // Add logging to check the payload values
            console.log(`Category: ${category}`);
            console.log(`Labels: ${labels}`);

            if (!category || !labels) {
              core.setFailed('Category or labels not found in the discussion payload.');
              return;
            }

            // Define allowed labels for each category under "Tickets" section
            const allowedLabels = {
              'ServiceNow': ['Incident', 'CHG'],
              'JIRA': ['bug', 'task', 'story']
            };

            // Check if the discussion category exists in the allowedLabels object
            if (allowedLabels[category]) {
              const requiredLabels = allowedLabels[category];

              // Check if any valid label is applied
              const hasValidLabel = labels.some(label => requiredLabels.includes(label));

              if (!hasValidLabel) {
                core.setFailed(`Invalid labels for category "${category}". Allowed labels are: ${requiredLabels.join(', ')}`);
              }
            } else {
              core.setFailed(`Invalid category "${category}". This category is not configured with allowed labels.`);
            }

      - name: Comment on discussion if invalid or empty labels
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.G_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.discussion.number }}
          body: |
            **Label issue detected for the category "${{ github.event.discussion.category.name }}".**
            Please use one of the allowed labels based on the discussion category:
            - For ServiceNow: "Incident", "Change Ticket"
            - For JIRA: "Bug", "Task", "Story"
            - **No discussion should be created without at least one valid label.**
